### ISSUE TITLE
selene oem unlock getServiceToken missing cookie

### ISSUE THREAD

**Issue by CastixGitHub** [francescotescari/XMT#85]
Device: Redmi 10 selene

more than 15 days since device->account connection

checked the account ID is the same (by mistake i previously logged into an old one)

unable to unlock

tool version: V20.7.28(beta)

(unable to copy the traceback since the text on screen is not selectable and no logs on stderr)

**Comment by Nik-Kot** [comment]
Download the latest version using `git clone https://github.com/francescotescari/XiaoMiToolV2.git` and run it with `gradlew run`. This issue is already fixed.

**Comment by paolomeraviglia** [comment]
![immagine](https://user-images.githubusercontent.com/15237168/207880677-9c9673ca-a5ba-4130-bcb2-d0c3c86e13c1.png)

tool version: latest dev branch, linux. I was trying to unlock the bootloader on a POCO f3

**Comment by rosembergdesantana** [comment]
Still not working, logging the code the response get in this method: httpGetServiceToken() in this class XiaomiServiceEntry.

        EasyResponse response;
        Log.log_private("Second step request: " + url);
        response = EasyHttp.get(url); -> 401 response code.
        HashMap<String, String> cookies = response.getCookies();
        serviceToken = cookies.get("serviceToken");

Always getting 401 after the request trying to get the url base mount in this method signedLocation().
